COMMON: &common
  SECRET_KEY: insecure
  SECURITY_POST_LOGIN: /profile
  SQLALCHEMY_DATABASE_URI: postgresql://postgres:password@127.0.0.1:5432/flask_social_example_development
    
DEVELOPMENT: &development
  <<: *common
  DEBUG: True

PRODUCTION: &production
  <<: *common
  DEBUG: True
  SECURITY_PASSWORD_HASH: bcrypt
  SOCIAL_APP_URL: http://flask-social-example.ep.io