COMMON: &common
  SECRET_KEY: insecure
  SECURITY_POST_LOGIN: /profile
  SQLALCHEMY_DATABASE_URI: postgresql://postgres:password@127.0.0.1:5432/flask_social_example_development
  ADMIN_CREDENTIALS: 'admin,password'

  SOCIAL_TWITTER:
    oauth:
      consumer_key: 'place holder'
      consumer_secret: 'place holder'

  SOCIAL_FACEBOOK:
    oauth:
      consumer_key: 'place holder'
      consumer_secret: 'place holder'
      request_token_params:
        scope: 'email,publish_stream'

DEVELOPMENT: &development
  <<: *common
  DEBUG: False

PRODUCTION: &production
  <<: *common
  DEBUG: True
  SECURITY_PASSWORD_HASH: bcrypt
  SOCIAL_APP_URL: http://flask-social-example.herokuapp.com/